3/ymp/config/routes.rb
Rails.application.routes.draw do
  resources :tabinfs
  root "tabinfs#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

3/ymp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

3/ymp/app/models/tabinf.rb
class Tabinf < ApplicationRecord
end

3/ymp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

3/ymp/app/controllers/tabinfs_controller.rb
class TabinfsController < ApplicationController
  before_action :set_tabinf, only: [:show, :edit, :update, :destroy]

  # GET /tabinfs
  # GET /tabinfs.json
  def index
    @tabinfs = Tabinf.all
  end

  # GET /tabinfs/1
  # GET /tabinfs/1.json
  def show
  end


  # GET /tabinfs/new
  def new
    @tabinf = Tabinf.new
  end

  # GET /tabinfs/1/edit
  def edit
  end

  # POST /tabinfs
  # POST /tabinfs.json
  def create
    @tabinf = Tabinf.new(tabinf_params)

    respond_to do |format|
      if @tabinf.save
        format.html { redirect_to @tabinf, notice: 'Tabinf was successfully created.' }
        format.json { render :show, status: :created, location: @tabinf }
      else
        format.html { render :new }
        format.json { render json: @tabinf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tabinfs/1
  # PATCH/PUT /tabinfs/1.json
  def update
    respond_to do |format|
      if @tabinf.update(tabinf_params)
        format.html { redirect_to @tabinf, notice: 'Tabinf was successfully updated.' }
        format.json { render :show, status: :ok, location: @tabinf }
      else
        format.html { render :edit }
        format.json { render json: @tabinf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tabinfs/1
  # DELETE /tabinfs/1.json
  def destroy
    @tabinf.destroy
    respond_to do |format|
      format.html { redirect_to tabinfs_url, notice: 'Tabinf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tabinf
      @tabinf = Tabinf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tabinf_params
      params.require(:tabinf).permit(:fio, :address, :ntel, :sex, :datro, :mestoro)
    end
end

3/ymp/app/helpers/application_helper.rb
module ApplicationHelper
end

3/ymp/app/helpers/tabinfs_helper.rb
module TabinfsHelper
end

3/ymp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ymp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

3/ymp/app/views/tabinfs/_form.html.erb
<%= form_for(tabinf) do |f| %>
  <% if tabinf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tabinf.errors.count, "error") %> prohibited this tabinf from being saved:</h2>

      <ul>
      <% tabinf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fio %>
    <%= f.text_area :fio %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.label :ntel %>
    <%= f.text_area :ntel %>
  </div>

  <div class="field">
    <%= f.label :sex %>
    <%= f.text_field :sex %>
  </div>

  <div class="field">
    <%= f.label :datro %>
    <%= f.date_select :datro %>
  </div>

  <div class="field">
    <%= f.label :mestoro %>
    <%= f.text_area :mestoro %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

3/ymp/app/views/tabinfs/edit.html.erb
<h1>Editing Tabinf</h1>

<%= render 'form', tabinf: @tabinf %>

<%= link_to 'Show', @tabinf %> |
<%= link_to 'Back', tabinfs_path %>

3/ymp/app/views/tabinfs/index.html.erb
<p id="notice"><%= notice %></p>



<h1>Tabinfs</h1>

<table>
  <thead>
    <tr>
      <th>Fio</th>
      <th>Address</th>
      <th>Ntel</th>
      <th>Sex</th>
      <th>Datro</th>
      <th>Mestoro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tabinfs.each do |tabinf| %>
      <tr>
        <td><%= tabinf.fio %></td>
        <td><%= tabinf.address %></td>
        <td><%= tabinf.ntel %></td>
        <td><%= tabinf.sex %></td>
        <td><%= tabinf.datro %></td>
        <td><%= tabinf.mestoro %></td>
        <td><%= link_to 'Show', tabinf %></td>
        <td><%= link_to 'Edit', edit_tabinf_path(tabinf) %></td>
        <td><%= link_to 'Destroy', tabinf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tabinf', new_tabinf_path %>

3/ymp/app/views/tabinfs/new.html.erb
<h1>New Tabinf</h1>

<%= render 'form', tabinf: @tabinf %>

<%= link_to 'Back', tabinfs_path %>

3/ymp/app/views/tabinfs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fio:</strong>
  <%= @tabinf.fio %>
</p>

<p>
  <strong>Address:</strong>
  <%= @tabinf.address %>
</p>

<p>
  <strong>Ntel:</strong>
  <%= @tabinf.ntel %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @tabinf.sex %>
</p>

<p>
  <strong>Datro:</strong>
  <%= @tabinf.datro %>
</p>

<p>
  <strong>Mestoro:</strong>
  <%= @tabinf.mestoro %>
</p>

<%= link_to 'Edit', edit_tabinf_path(@tabinf) %> |
<%= link_to 'Back', tabinfs_path %>